### ISSUE TITLE
doesn't seem to auto start on centos/amazon linux

### ISSUE THREAD

**Issue by aarondodd** [SimpleFinance/chef-zookeeper#71]
I'm running amazon linux (centos) and while Exhibitor and Zookeeper start fine if I manually execute the exec line of /etc/init/exhibitor.conf, the recipe itself hangs at 

Recipe: zookeeper::exhibitor
  * service[exhibitor] action stop (up to date)
  * service[exhibitor] action start
    - start service service[exhibitor]

for 5+ minutes before reporting a successful finish.  But, chef doesn't actually start it.  a ps shows no java running or anything for exhibitor.

issuing "start exhibitor" seems to just hang and not do anything.

**Comment by zanzan42** [comment]
I'm still having issues with zookeeper starting when the zookeeper::service recipe is run under OpsWorks with the upstart provider set. The command which the recipe runs is /sbin/start zookeeper, and that fails. Running that manually returns a no such job found error.

Using the runit provider starts the service, but then I get issues with the leader election process because it doesn't seem to have listeners at 2888/3888 for the quorum stuff.

Looks like this recipe doesn't include functionality related to zookeeper clustering, in general. I had to do a supplemental recipe to lay down the myid file, for instance.
